export const images = {
    rightArrow: require('./right-arrow-icon.png'),
    leftArrow: require('./left-arrow-icon.png'),
    filterListDown: require('./filter-list-down-icon.png'),
    filterListUp: require('./filter-list-up-icon.png'),
    logout: require('./logout-icon.png'),
    asRead: require('./as-read-icon.png'),
    search: require('./search-icon.png'),
    delete: require('./delete-icon.png'),
    favoriteOn: require('./favorite-on-icon.png'),
    favoriteOff: require('./favorite-off-icon.png'),
    goBack: require('./goback-icon.png'),
    loginBackground : require('./login-background.jpg'),
    loginBackgroundDBZ : require('./login-background-dbz.jpg'),
    loginBackgroundOP : require('./login-background-one-piece.jpg'),
};